### ISSUE TITLE
Meer info in boeien.gpx

### ISSUE THREAD

**Issue by PietKnot** [marcelrv/OpenCPN-Waypoints#2]
Hoi Marcel,

mijn eigen scriptje (losse bestanden per regio) geeft wat extra info over de boeien: vooral <name>  zou handig zijn om die ook toe te voegen in jouw dagelijkse update van NL-Boeien.gpx. De andere info: <cmt>, <desc> enz. kan ook geen kwaad.

<wpt lat="51.635550000" lon="4.253019440">
    <name>SV 1</name>
    <cmt>STEENBERGSCHE VLIET</cmt>
    <desc>Groen</desc>
    <sym>spar</sym>

**Comment by PietKnot** [comment]
sorry, op de een-of-andere manier is de extra info verloren gegaan:
<wpt lat="51.635550000" lon="4.253019440">
    <name>SV 1</name>
    <cmt>STEENBERGSCHE VLIET</cmt>
    <desc>Groen</desc>
    <sym>spar</sym>
  </wpt>

**Comment by PietKnot** [comment]
sorry, op de een-of-andere manier is de info verloreen gegaan; nu als "add code":
`<wpt lat="51.635550000" lon="4.253019440">
    <name>SV 1</name>
    <cmt>STEENBERGSCHE VLIET</cmt>
    <desc>Groen</desc>
    <sym>spar</sym>
  </wpt>`

**Comment by marcelrv** [comment]
hallo Piet,
ik zie dat er idd een probleempje is met het runnen op het moment.
Het friesland bestand heeft de info, maar in het gewone bestand NL is het weggevallen. 

Ik ga kijken wat er aan de hand is

**Comment by marcelrv** [comment]
fixed with 73954d5
Heb het issue gevonden, Kijk ff of je nu de info hebt die je verwacht.. Als je er nog mis reopen issue.
Extra velden zijn eenvoudig toe te voegen door in het lijstje te zetten
https://github.com/marcelrv/OpenCPN-Waypoints/blob/main/boeien_gen_def.py#L33:L40

**Comment by PietKnot** [comment]
Zal het doen; helaas zelf een old-fashioned programmer zonder java / phyton ervaring, maar mogelijk begrijp ik de source-code. 

Checked: all fine, hardstikke bedankt!!
