### ISSUE TITLE
Voeg telefoon nummer toe aan de haven

### ISSUE THREAD

**Issue by PietKnot** [marcelrv/OpenCPN-Waypoints#3]
Marcel,

ik zelf heb geen scriptje voor de jachthavens, maar het zou handig zijn als bij de NL jachthavens, ook het telefoon-nummer opgenomen zou worden bij de Description van de jachthaven (net zoals  "passanten ligplaatsen" /  "vaste ligplaatsen" /  "Tankstation" ). Dan is off-line toegang mogelijk i.p.v via de link de info op te halen.

**Comment by marcelrv** [comment]
ja, dat is zeker handig.
Weet niet zeker of / hoe die info ook aan de records gelikt staan. (staat niet direct in het haven record).
Zal kijken of ik het kan vinden

**Comment by marcelrv** [comment]
Waar voorhanden is het telefoon nr nu toegevoegd aan de havens en bruggen.
Ik zie wel veel havens waar deze info mist, maar in dat geval mist ie ook in de online info.. 
Je punt mbt offline is hiermee zover mogelijk in iedergeval opgelost.

closed with 134ad29

**Comment by PietKnot** [comment]
Fantastisch: werkt en bedankt!
